### ISSUE TITLE
Feature Request: STEP/IGES For Scan Rig

### ISSUE THREAD

**Issue by kickhad** [alicevision/ScanRig#2]
It would be great to have the CAD file used in your rendering of the scan rig. I plan on creating many parametric 3D Printable parts with whatever scanning rig I set up.

**Comment by guillaume-haerinck** [comment]
Hi ! I just added the Fusion360 archive and the STEP export into the `previs` folder (b2b7c4bd523a3c4e54bacf8eb230c635706f58b4). You can also access the model online with the [fusion viewer](https://a360.co/2V5fdnj).

Thanks for the request.
